# Generated by Django 4.0.4 on 2022-06-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_workexperience_education1_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='ken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ken'),
        ),
    ]
